package com.example.demo.exception;

public enum ErrorCode {

    // Authentication
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    ACCESS_DENIED,
    INVALID_TOKEN,
    TOKEN_EXPIRED,
    REFRESH_TOKEN_INVALID,

    // User
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,

    // Validation
    VALIDATION_ERROR,

    // Documents
    DOCUMENT_NOT_FOUND,
    DOCUMENT_UPLOAD_FAILED,
    DOCUMENT_PROCESSING_FAILED,

    // Generic
    BUSINESS_ERROR,
    DUPLICATE_EMAIL, REFRESH_TOKEN_EXPIRED, REFRESH_TOKEN_NOT_FOUND, REFRESH_TOKEN_REVOKED, INTERNAL_SERVER_ERROR
}
